version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: "postgres://mydjango:secret@db:5432/djangodb"
    volumes:
      - .:/usr/src/app
    command: "python manage.py runserver 0:8000"
  db:
    image: postgres:14
    volumes:
      - ./docker/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=mydjango
      - POSTGRES_PASSWORD=secret
